# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.b2bOrg.logistics:
  peer1.b2bOrg.logistics:

networks:
  b2b:

services:

  #  orderer.example.com:
  #  extends:
  #    file:   docker-compose-base.yaml
  #    service: orderer.orderer.com
  #  container_name: orderer.orderer.com
  #  networks:
  #    - b2b

  #peer0.b2bOrg.logistics:
  #  container_name: peer0.b2bOrg.logistics
  #  extends:
  #    file:  docker-compose-base.yaml
  #    service: peer0.b2bOrg.logistics
  #  networks:
  #    - b2b

  #peer1.b2bOrg.logistics:
  #  container_name: peer1.b2bOrg.logistics
  #  extends:
  #    file:  docker-compose-base.yaml
  #    service: peer1.b2bOrg.logistics
  #  networks:
  #    - b2b


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      #- SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.b2bOrg.logistics:7051
      - CORE_PEER_LOCALMSPID=b2bOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/b2bOrg.logistics/peers/peer0.b2bOrg.logistics/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/b2bOrg.logistics/peers/peer0.b2bOrg.logistics/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/b2bOrg.logistics/peers/peer0.b2bOrg.logistics/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/b2bOrg.logistics/users/Admin@b2bOrg.logistics/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          #- ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          #    depends_on:
          #- orderer.orderer.com
          # - peer0.b2bOrg.logistics
          #- peer1.b2bOrg.logistics
    networks:
      - b2b
